#!/usr/bin/env python3
"""Completion: predicate evaluation, run binding, artifact settlement, integration, depth.

This module is the first consumer of :func:`session_lifecycle.check_completion_scope` and the
only place a child reaches ``verified``.  Evidence integrity is the highest-severity failure
category in this plugin because a false *pass* is indistinguishable from a true one downstream,
so every control here is written to fail closed and to claim only what it actually enforces.

What each control proves, and what it does not
----------------------------------------------
**Settlement is performed by the orchestrator, not asserted about the child.**  A file on disk
does not record whether it arrived by rename or by direct write -- ``stat`` does not carry it and
content does not carry it -- so a check that reads the finished artifact can never establish it.
Instead the child writes only to an *in-flight sibling* of the destination, and this module
performs the rename itself with :func:`os.replace`.  The destination is required to be
byte-for-byte the state recorded before dispatch, so a child that wrote the destination directly
is rejected with a real signal rather than a guess.  Because the in-flight path is a sibling of
the destination it is always on the same filesystem, so the rename is a rename and never a copy.
The predicate therefore only ever reads a path this module renamed into place.  Settlement is
recorded durably and replayed on a later evaluation of the same dispatch, because the rename is
one-shot: after it, "already settled correctly" and "written directly by the child" look identical
on disk, and only the record separates them.  What is **not** claimed: that the child produced the
in-flight file atomically.  A child that writes its in-flight file slowly is fine, because nothing
reads it until the rename.

**Run binding is established before dispatch and compared afterwards.**  The expected identity is
a token generated by the orchestrator before the child runs and stored in the register; the
artifact must carry that exact token.  It is never read from a file beside the artifact, because a
stale receipt from a previous run would then satisfy a comparison against itself.

**The durable records are authenticated, because the register is not a trusted store.**  Every
child can write files in its landing, the register is inside every child's landing, and it is
Git-ignored -- so the boundary check does not observe a child that rewrites it.  The dispatch
receipt and the settlement record therefore each carry a keyed digest under a per-run secret held
outside the repository (:func:`run_secret`).  A record the orchestrator did not write does not
authenticate, and nothing it claims is believed.  A child can still *delete* those records, and
then nothing verifies -- which is the correct failure.

**Predicate integrity is static and dynamic.**  Statically, the predicate's entry points *and its
resolvable import closure* -- including the parent package initializers Python executes on the way
to a submodule -- must lie outside everything the child may write.  Dynamically, a digest over the
closure's contents is captured before dispatch and re-checked before evaluation, so a change to
any statically known closure file is caught even if the file sits outside the child's declared
scope.  What is **not** covered is enumerated, member by member, in ``references/predicates.md``.

**The observer must not disturb the evidence.**  The predicate runs inline, in the child's
landing, after the child stopped.  Anything it writes there would otherwise be attributed to the
child by the boundary check, so the landing is snapshotted immediately before the predicate runs
and any predicate-authored change is a failure of the predicate, never of the child.  The
artifact directory is snapshotted alongside it, because that directory is deliberately invisible
to Git and an observer that cannot see the evidence is not observing the evidence.

Ordering
--------
Identity first: the specification, landing and receipt arrive as independent arguments, and a
receipt that belongs to a different child is refused before anything else is read.  Then evidence
integrity, short-circuiting (tamper, settlement, binding), because an unsettled or unbound
artifact is not evidence and there is nothing to evaluate.  Then the predicate outcome and the
boundary check, computed independently -- a boundary violation fails completion even when the
predicate passed.  Then integration, then the judgment-work depth sample.

Evaluation is re-runnable for one dispatch, and the phase follows the verdict: a row is
``verified`` if and only if its latest recorded verdict is a pass.
"""

from __future__ import annotations

import ast
import hashlib
import hmac
import json
import os
import re
import secrets
import stat as stat_module
import subprocess  # nosec B404 -- fixed argv, no shell
import tempfile
import time
import uuid
from collections.abc import Mapping, Sequence
from dataclasses import dataclass, replace
from pathlib import Path, PurePosixPath
from typing import Any

import register as register_store
import session_lifecycle

fleet_commons_shim = session_lifecycle.fleet_commons_shim
tier_resolver = session_lifecycle.tier_resolver

# --------------------------------------------------------------------------- constants

#: Suffix of the sibling path a child writes.  A sibling is always on the destination's own
#: filesystem, which is what makes :func:`os.replace` a rename rather than a copy.
INFLIGHT_SUFFIX = ".orchestrate-inflight"

#: Per-child exclusive artifact directory, relative to the child's own landing.
ARTIFACTS_SEGMENTS = ("artifacts",)

#: The run binding a child must carry inside its deliverable.
#:
#: Deliberately flat and escape-free rather than the JSON-payload sentinel U3 uses for pane
#: output: a token containing quotes and braces is re-escaped when a child embeds it in a JSON,
#: YAML, or XML deliverable, so an exact-substring comparison against a correct artifact would
#: fail.  Every component is already constrained to ``[A-Za-z0-9._-]``, so the token survives
#: embedding in any text format unchanged.
ARTIFACT_BINDING_PREFIX = "ORCHESTRATE-ARTIFACT-BINDING"
_BINDING_RE = re.compile(
    rf"{ARTIFACT_BINDING_PREFIX}:([A-Za-z0-9._-]+):([A-Za-z0-9._-]+):([A-Za-z0-9._-]+)"
)

#: Schema bounds.  A predicate declaring more than these is rejected, not clamped.
DEFAULT_TIMEOUT_SECONDS = 120.0
MAX_TIMEOUT_SECONDS = 900.0
DEFAULT_MAX_OUTPUT_BYTES = 256 * 1024
MAX_OUTPUT_BYTES = 4 * 1024 * 1024
DEFAULT_MAX_ARTIFACT_BYTES = 8 * 1024 * 1024

#: Static closure analysis bounds.  Exceeding either is a hard failure, never a truncation.
MAX_CLOSURE_FILES = 512
MAX_CLOSURE_BYTES = 8 * 1024 * 1024

#: Interpreters whose ``-c`` form is shell or source text smuggled through an argument vector.
_TEXT_EXECUTION_FLAGS = frozenset({"-c", "--command", "-e"})
_SHELLS = frozenset(
    {"sh", "bash", "zsh", "dash", "ksh", "csh", "tcsh", "fish", "cmd", "powershell"}
)

#: Programs whose whole job is to launch a *different* program.  Rejecting only shells would let
#: ``["/usr/bin/env", "sh", "check.sh"]`` run a shell straight past a check that reads ``argv[0]``,
#: and in every such case the predicate's real program is unknowable to the closure analysis.  A
#: predicate names its program directly.
_INDIRECTION_WRAPPERS = frozenset(
    {"env", "nohup", "nice", "setsid", "timeout", "xargs", "stdbuf", "sudo", "doas", "exec"}
)

#: Judgment-shaped work, resolved through U1's authoritative work-shape vocabulary rather than a
#: locally invented list.  ``adversarial-review`` reaches this set through U1's role-tier alias.
JUDGMENT_WORK_SHAPES = frozenset({"judgment", "second-opinion", "divergence"})

#: Closed disposition vocabulary for one sampled claim.
DEPTH_DISPOSITIONS = ("supported", "unsupported", "inconclusive")

#: Register keys this module owns, and the authentication field carried inside both of them.
SETTLEMENT_KEY = "settlement"
DISPATCH_RECEIPT_KEY = "dispatch_receipt"
AUTHENTICATION_KEY = "authentication"

#: Where the per-run orchestrator secret lives, and the environment variable that relocates it.
#:
#: It must be outside the repository, because every child's landing is *inside* the repository:
#: a read-only child's landing is the ambient checkout itself, and a mutating child's is a
#: worktree under ``.orchestrate/``.  A workspace-write posture is the one containment the
#: supported CLIs actually express, so a secret outside the workspace is the one place a child's
#: own launch flags keep it out of.
RUN_SECRET_DIR_ENV = "ORCHESTRATE_RUN_SECRET_DIR"
DEFAULT_RUN_SECRET_DIR = Path("~/.orchestrate/run-secrets")
RUN_SECRET_BYTES = 32

#: Closed failure vocabulary.  Every one is a refusal to verify; there is no "warn" outcome.
FAILURE_REASONS = (
    "receipt_mismatch",
    "predicate_tampered",
    "artifact_unsettled",
    "artifact_binding",
    "predicate_failed",
    "predicate_timeout",
    "predicate_output_limit",
    "predicate_error",
    "predicate_side_effect",
    "scope_violation",
    "integration_unverified",
    "depth_sample_missing",
    "depth_sample_invalid",
    "depth_sample_unsupported",
    "depth_sample_inconclusive",
)

_SAFE_COMPONENT_RE = re.compile(r"^[A-Za-z0-9._-]+$")


# --------------------------------------------------------------------------- errors


class CompletionError(RuntimeError):
    """Base error for completion evaluation."""


class PredicateSchemaError(CompletionError):
    """A predicate declaration is not the typed, closed schema."""


class PredicateClosureError(CompletionError):
    """A predicate's dependency closure cannot be established within its bounds."""


class PredicateScopeError(CompletionError):
    """A predicate's script or dependency closure lives where the child may write."""


class ArtifactError(CompletionError):
    """An artifact is unsettled, unbound, or outside its exclusive landing."""


class LandingNotExclusiveError(CompletionError):
    """The per-child artifact landing is not invisible to the repository boundary."""


class DepthSampleError(CompletionError):
    """A judgment-shaped child's depth sample is missing, malformed, or unattributable."""


class RunSecretError(CompletionError):
    """The per-run orchestrator secret is missing, unreadable, or reachable by a child."""


class ReceiptAuthenticationError(CompletionError):
    """A durable record in the register was not written by the orchestrator that issued it."""


# --------------------------------------------------------------------------- predicate schema


@dataclass(frozen=True)
class PredicateSpec:
    """A bounded mechanical check declared as a fixed argument vector.

    The schema is *closed*: an unknown key is an error rather than an ignored field, because a
    silently ignored ``shell`` or ``timeout`` key is exactly how an unbounded check reaches
    production looking bounded.
    """

    argv: tuple[str, ...]
    timeout_seconds: float = DEFAULT_TIMEOUT_SECONDS
    max_output_bytes: int = DEFAULT_MAX_OUTPUT_BYTES

    ALLOWED_KEYS = ("argv", "timeout_seconds", "max_output_bytes")

    def __post_init__(self) -> None:
        if not self.argv:
            raise PredicateSchemaError("predicate argv must contain at least the program")
        for item in self.argv:
            if not isinstance(item, str) or not item:
                raise PredicateSchemaError(
                    "every predicate argv element must be a non-empty string"
                )
        program = PurePosixPath(self.argv[0]).name
        if program in _INDIRECTION_WRAPPERS:
            raise PredicateSchemaError(
                f"predicate program {self.argv[0]!r} launches another program; name the real "
                "program directly so its dependency closure can be established"
            )
        if program in _SHELLS:
            raise PredicateSchemaError(
                f"predicate program {self.argv[0]!r} is a shell; a predicate is an argument "
                "vector, not shell text"
            )
        if any(flag in _TEXT_EXECUTION_FLAGS for flag in self.argv[1:]):
            raise PredicateSchemaError(
                "predicate argv carries an inline-source flag "
                f"({sorted(_TEXT_EXECUTION_FLAGS)}); a predicate must be a program and its "
                "arguments, so its dependency closure can be established"
            )
        if not 0 < self.timeout_seconds <= MAX_TIMEOUT_SECONDS:
            raise PredicateSchemaError(
                f"predicate timeout_seconds must be in (0, {MAX_TIMEOUT_SECONDS}]"
            )
        if not 0 < self.max_output_bytes <= MAX_OUTPUT_BYTES:
            raise PredicateSchemaError(
                f"predicate max_output_bytes must be in (0, {MAX_OUTPUT_BYTES}]"
            )

    @classmethod
    def from_mapping(cls, value: Any) -> PredicateSpec:
        """Build a spec from a register/JSON declaration, rejecting anything else."""
        if isinstance(value, str):
            raise PredicateSchemaError(
                "a predicate declared as text is rejected; declare an 'argv' array so the check "
                "runs without a shell and its dependency closure can be established"
            )
        if not isinstance(value, Mapping):
            raise PredicateSchemaError("a predicate declaration must be a JSON object")
        unknown = sorted(set(value) - set(cls.ALLOWED_KEYS))
        if unknown:
            raise PredicateSchemaError(
                f"unknown predicate keys {unknown}; the schema is closed and allows "
                f"{list(cls.ALLOWED_KEYS)}"
            )
        argv = value.get("argv")
        if isinstance(argv, str):
            raise PredicateSchemaError(
                "predicate argv must be an array of arguments, not a command string"
            )
        if not isinstance(argv, Sequence):
            raise PredicateSchemaError("predicate argv must be an array of arguments")
        timeout = value.get("timeout_seconds", DEFAULT_TIMEOUT_SECONDS)
        output_cap = value.get("max_output_bytes", DEFAULT_MAX_OUTPUT_BYTES)
        if isinstance(timeout, bool) or not isinstance(timeout, int | float):
            raise PredicateSchemaError("predicate timeout_seconds must be a number")
        if isinstance(output_cap, bool) or not isinstance(output_cap, int):
            raise PredicateSchemaError("predicate max_output_bytes must be an integer")
        return cls(tuple(argv), float(timeout), int(output_cap))

    def to_mapping(self) -> dict[str, Any]:
        return {
            "argv": list(self.argv),
            "timeout_seconds": self.timeout_seconds,
            "max_output_bytes": self.max_output_bytes,
        }


# --------------------------------------------------------------------------- closure analysis


def _repo_relative(workdir: Path, path: Path) -> str | None:
    try:
        return path.resolve().relative_to(workdir.resolve()).as_posix()
    except ValueError:
        return None


#: Suffixes of an importable module file.  Native extensions are included so an in-tree ``.so``
#: at least enters the closure and is digested, even though nothing can follow *its* imports.
_MODULE_SUFFIXES = (".py", ".so", ".pyd")


def _module_candidates(module: str, search_roots: Sequence[Path]) -> list[Path]:
    """Every in-tree file Python would execute to satisfy ``import module``.

    That includes each **parent package initializer** along the dotted path, not just the leaf.
    For ``import pkg.oracle`` Python executes ``pkg/__init__.py`` before ``pkg/oracle.py``, so a
    closure holding only the leaf lets a child whose scope is exactly ``pkg/__init__.py`` change
    what ``pkg.oracle`` resolves to -- in scope, with the closure digest unchanged.  A package
    with no initializer (PEP 420 namespace package) simply contributes no such file, which is why
    the candidates are filtered by existence rather than required to exist.
    """
    parts = module.split(".")
    candidates: list[Path] = []
    for root in search_roots:
        for depth in range(1, len(parts)):
            candidates.append(root.joinpath(*parts[:depth]) / "__init__.py")
        base = root.joinpath(*parts)
        for suffix in _MODULE_SUFFIXES:
            candidates.append(base.with_suffix(suffix))
        candidates.append(base / "__init__.py")
    return candidates


def _relative_package_root(source: Path, level: int) -> Path:
    root = source.parent
    for _ in range(level - 1):
        root = root.parent
    return root


def _imported_files(source: Path, workdir: Path) -> set[Path]:
    """Resolve one Python file's static imports to files inside ``workdir``.

    Only statements the parser can see are followed.  Everything a module reaches by dynamic
    import, ``sys.path`` manipulation, or data-file read is outside this analysis and is declared
    as such in ``references/predicates.md``.
    """
    try:
        tree = ast.parse(source.read_text(encoding="utf-8", errors="replace"), filename=str(source))
    except SyntaxError as exc:
        raise PredicateClosureError(
            f"predicate closure member {source} does not parse: {exc}"
        ) from exc
    found: set[Path] = set()
    for node in ast.walk(tree):
        candidates: list[Path] = []
        if isinstance(node, ast.Import):
            for alias in node.names:
                candidates.extend(_module_candidates(alias.name, (source.parent, workdir)))
        elif isinstance(node, ast.ImportFrom):
            if node.level:
                package_root = _relative_package_root(source, node.level)
                roots: tuple[Path, ...] = (package_root,)
            else:
                roots = (source.parent, workdir)
            if node.module:
                candidates.extend(_module_candidates(node.module, roots))
            for alias in node.names:
                name = f"{node.module}.{alias.name}" if node.module else alias.name
                candidates.extend(_module_candidates(name, roots))
        for candidate in candidates:
            if candidate.is_file() and _repo_relative(workdir, candidate) is not None:
                found.add(candidate.resolve())
    return found


def predicate_closure(
    workdir: Path,
    predicate: PredicateSpec,
    *,
    max_files: int = MAX_CLOSURE_FILES,
    subject: str | None = None,
) -> tuple[str, ...]:
    """Return every file inside ``workdir`` the predicate is known to depend on.

    Roots are the argument-vector elements that resolve to a real path inside ``workdir`` -- both
    the entry-point script and path arguments such as a test file or directory, because for a
    runner like ``pytest`` the arguments *are* the check.  Python roots are then followed through
    their static import statements, transitively.

    ``subject`` is the artifact under judgement.  It is data the check reads, not code that
    decides what the check does, so it is excluded from the closure -- otherwise every predicate
    would be rejected for depending on the very file it exists to inspect.  A predicate that
    *executes* its subject is refused outright, and a predicate that statically imports it is
    still caught, because the import is discovered from another closure member.

    Bounded on purpose: exceeding ``max_files`` or the byte cap raises rather than truncating,
    because a silently truncated closure is a control that reports a narrower dependency set than
    the real one.
    """
    workdir = workdir.resolve()
    if subject is not None and PurePosixPath(predicate.argv[0]) == PurePosixPath(subject):
        raise PredicateClosureError(
            f"predicate program {predicate.argv[0]!r} is the artifact it judges; a check the "
            "child authors is not a check"
        )
    pending: list[Path] = []
    for item in predicate.argv:
        if item.startswith("-") or (subject is not None and item == subject):
            continue
        candidate = (workdir / item).resolve()
        if _repo_relative(workdir, candidate) is None or not candidate.exists():
            continue
        if candidate.is_dir():
            members = sorted(candidate.rglob("*.py"))
            if len(members) > max_files:
                raise PredicateClosureError(
                    f"predicate path argument {item!r} expands to {len(members)} Python files, "
                    f"above the {max_files}-file closure bound"
                )
            pending.extend(members)
        else:
            pending.append(candidate)

    seen: set[Path] = set()
    total_bytes = 0
    while pending:
        current = pending.pop()
        if current in seen:
            continue
        seen.add(current)
        if len(seen) > max_files:
            raise PredicateClosureError(
                f"predicate dependency closure exceeds {max_files} files; declare a narrower "
                "predicate rather than accepting an unbounded closure"
            )
        total_bytes += current.stat().st_size
        if total_bytes > MAX_CLOSURE_BYTES:
            raise PredicateClosureError(
                f"predicate dependency closure exceeds {MAX_CLOSURE_BYTES} bytes"
            )
        if current.suffix == ".py":
            pending.extend(_imported_files(current, workdir))

    relative = {_repo_relative(workdir, path) for path in seen}
    return tuple(sorted(item for item in relative if item is not None))


def closure_digest(workdir: Path, predicate: PredicateSpec, closure: Sequence[str]) -> str:
    """Digest the predicate declaration together with the contents of its closure."""
    digest = hashlib.sha256()
    digest.update(json.dumps(predicate.to_mapping(), sort_keys=True).encode("utf-8"))
    for relative in sorted(closure):
        digest.update(b"\0" + relative.encode("utf-8") + b"\0")
        path = workdir / relative
        if not path.is_file():
            digest.update(b"missing")
            continue
        with path.open("rb") as stream:
            while chunk := stream.read(1024 * 1024):
                digest.update(chunk)
    return "sha256:" + digest.hexdigest()


def assert_predicate_outside_write_scope(
    closure: Sequence[str], write_scope: Sequence[str]
) -> None:
    """Refuse a predicate the child it certifies could rewrite.

    ``write_scope`` is every location the child may write: its declared repository scope when it
    is a mutating child, plus its own exclusive artifact landing in every case.  Checking only the
    entry-point path would leave a predicate that *imports* a module inside the scope exactly as
    compromised as one that lives there.
    """
    normalized = session_lifecycle.normalize_scope(write_scope)
    inside = sorted(path for path in closure if session_lifecycle.path_in_scope(path, normalized))
    if inside:
        raise PredicateScopeError(
            "predicate dependency closure lives inside the child's write scope and could be "
            "weakened by the child it certifies: " + ", ".join(inside)
        )


# --------------------------------------------------------------------------- authentication


def _safe_component(value: str, *, label: str) -> str:
    if not value or not _SAFE_COMPONENT_RE.match(value):
        raise CompletionError(f"{label} {value!r} must be a non-empty [A-Za-z0-9._-]+ token")
    return value


def run_secret_dir() -> Path:
    """Where this host keeps per-run orchestrator secrets."""
    override = os.environ.get(RUN_SECRET_DIR_ENV)
    return Path(override).expanduser() if override else DEFAULT_RUN_SECRET_DIR.expanduser()


def run_secret(root: Path, run_id: str, *, create: bool = True) -> bytes:
    """Load -- or, for a new run, mint -- the secret that authenticates this run's durable records.

    **The threat this defeats.**  The register lives at ``.orchestrate/register.json``, which is
    Git-ignored, and Git-ignored means invisible to the boundary check: a child that writes it is
    not observed by any control this plugin has.  Every child can write files in its landing, and
    the register is inside every child's landing.  So the durable dispatch receipt -- the copy a
    restarted orchestrator must read, and the only reason the receipt is persisted at all -- sits
    somewhere the child it is supposed to bind can rewrite.  A child that replaces the binding
    token with one it already holds, or replaces the predicate with ``/usr/bin/true`` and
    recomputes the closure digest so the tamper check agrees, satisfies a receipt it wrote itself.
    Both were demonstrated against this module before this control existed.

    Inspection cannot close that, because a forged record and a genuine one are the same bytes in
    the same place.  Authentication can: the record carries a keyed digest over its own fields,
    and the key never enters any child's landing.  A child can still *destroy* the receipt -- and
    then nothing verifies, which is the correct failure.

    **What the key rests on.**  The secret lives outside the repository, and that location is
    checked rather than assumed.  A workspace-write posture is the one containment the supported
    CLIs genuinely express, so "outside the workspace" is the one boundary a child's own launch
    flags enforce.  Two runtimes -- Claude and Muse -- get no positive flag at all, so for those
    the separation rests on the child never being pointed at the directory rather than on a
    sandbox refusing it; that is weaker and is stated rather than papered over.
    """
    directory = run_secret_dir().resolve()
    root_resolved = root.resolve()
    if directory == root_resolved or root_resolved in directory.parents:
        raise RunSecretError(
            f"the run-secret directory {directory} is inside the repository at {root_resolved}; "
            "every child's landing is inside that repository, so a secret stored there is "
            "writable by the very children it authenticates"
        )
    path = directory / f"{_safe_component(run_id, label='run_id')}.key"
    if path.exists():
        info = path.lstat()
        if stat_module.S_ISLNK(info.st_mode):
            raise RunSecretError(f"run secret {path} is a symlink; it must be a regular file")
        if info.st_mode & 0o077:
            raise RunSecretError(
                f"run secret {path} is accessible beyond its owner (mode "
                f"{stat_module.S_IMODE(info.st_mode):04o}); refusing to authenticate against a "
                "secret another account can read or replace"
            )
        material = path.read_bytes()
        if len(material) < RUN_SECRET_BYTES:
            raise RunSecretError(f"run secret {path} is shorter than {RUN_SECRET_BYTES} bytes")
        return material
    if not create:
        raise RunSecretError(
            f"no orchestrator secret exists for run {run_id!r} at {path}; a durable record "
            "claiming that run cannot be authenticated"
        )
    directory.mkdir(parents=True, exist_ok=True, mode=0o700)
    material = secrets.token_bytes(RUN_SECRET_BYTES)
    try:
        handle = os.open(path, os.O_WRONLY | os.O_CREAT | os.O_EXCL, 0o600)
    except FileExistsError:
        # A concurrent orchestrator minted it first; its secret is the run's secret.
        return run_secret(root, run_id, create=False)
    try:
        os.write(handle, material)
        os.fsync(handle)
    finally:
        os.close(handle)
    return material


def _signature(payload: Mapping[str, Any], secret: bytes) -> str:
    canonical = json.dumps(payload, sort_keys=True, separators=(",", ":"), default=str)
    return "hmac-sha256:" + hmac.new(secret, canonical.encode("utf-8"), hashlib.sha256).hexdigest()


def _seal(payload: Mapping[str, Any], secret: bytes) -> dict[str, Any]:
    """Return ``payload`` plus a keyed digest over exactly the fields it carries."""
    return {**payload, AUTHENTICATION_KEY: _signature(payload, secret)}


def _unseal(stored: Mapping[str, Any], secret: bytes, *, label: str) -> dict[str, Any]:
    """Return the authenticated fields of ``stored``, or refuse.

    The digest covers the stored mapping *as stored*, minus the signature itself, so a key added
    to the record is a mismatch rather than a field that is quietly ignored on the way back into
    a typed object.
    """
    presented = stored.get(AUTHENTICATION_KEY)
    payload = {key: value for key, value in stored.items() if key != AUTHENTICATION_KEY}
    if not isinstance(presented, str) or not presented:
        raise ReceiptAuthenticationError(
            f"the stored {label} carries no authentication; it was not written by an orchestrator "
            "that held this run's secret"
        )
    if not hmac.compare_digest(_signature(payload, secret), presented):
        raise ReceiptAuthenticationError(
            f"the stored {label} did not authenticate against this run's orchestrator secret; it "
            "was altered after it was written, or written by something that is not the "
            "orchestrator"
        )
    return payload


# --------------------------------------------------------------------------- receipt


def artifact_binding_token(run_id: str, row_id: str, nonce: str) -> str:
    """The expected identity of one dispatch's deliverable, generated before the child runs."""
    return ":".join(
        (
            ARTIFACT_BINDING_PREFIX,
            _safe_component(run_id, label="run_id"),
            _safe_component(row_id, label="row_id"),
            _safe_component(nonce, label="nonce"),
        )
    )


def artifact_landing(landing_cwd: Path, run_id: str, row_id: str) -> Path:
    """Return the child's exclusive artifact directory inside its own landing.

    It lives *inside the landing* rather than beside the repository so a sandboxed mutating child
    can write to it at all, and it is required to be invisible to Git so two read-only children
    sharing one checkout stop being attributed each other's output.
    """
    return (
        register_store.orchestrate_dir(landing_cwd)
        .joinpath(*ARTIFACTS_SEGMENTS)
        .joinpath(_safe_component(run_id, label="run_id"), _safe_component(row_id, label="row_id"))
    )


def _path_state(path: Path) -> dict[str, Any]:
    """A comparable record of what is at ``path`` right now, symlinks not followed."""
    try:
        stat = path.lstat()
    except FileNotFoundError:
        return {"exists": False}
    if not os.path.isfile(path) or os.path.islink(path):
        return {"exists": True, "kind": "not-a-regular-file", "mode": stat.st_mode}
    digest = hashlib.sha256()
    with path.open("rb") as stream:
        while chunk := stream.read(1024 * 1024):
            digest.update(chunk)
    return {
        "exists": True,
        "kind": "file",
        "size": stat.st_size,
        "digest": "sha256:" + digest.hexdigest(),
    }


@dataclass(frozen=True)
class DispatchReceipt:
    """The expected identity of one dispatch's evidence, established before the child runs."""

    run_id: str
    row_id: str
    landing_cwd: str
    artifact_relpath: str
    binding_token: str
    nonce: str
    destination_state: dict[str, Any]
    predicate: PredicateSpec
    predicate_closure: tuple[str, ...]
    predicate_digest: str
    write_scope: tuple[str, ...]
    integration_mode: str
    destination: str
    destination_pre_state: dict[str, Any]
    base_commit: str | None
    issued_at: float

    @property
    def artifact_path(self) -> Path:
        return Path(self.landing_cwd) / self.artifact_relpath

    @property
    def inflight_path(self) -> Path:
        return self.artifact_path.with_name(self.artifact_path.name + INFLIGHT_SUFFIX)

    def to_mapping(self) -> dict[str, Any]:
        return {
            "run_id": self.run_id,
            "row_id": self.row_id,
            "landing_cwd": self.landing_cwd,
            "artifact_relpath": self.artifact_relpath,
            "binding_token": self.binding_token,
            "nonce": self.nonce,
            "destination_state": self.destination_state,
            "predicate": self.predicate.to_mapping(),
            "predicate_closure": list(self.predicate_closure),
            "predicate_digest": self.predicate_digest,
            "write_scope": list(self.write_scope),
            "integration_mode": self.integration_mode,
            "destination": self.destination,
            "destination_pre_state": self.destination_pre_state,
            "base_commit": self.base_commit,
            "issued_at": self.issued_at,
        }

    @classmethod
    def from_mapping(cls, value: Mapping[str, Any]) -> DispatchReceipt:
        return cls(
            run_id=str(value["run_id"]),
            row_id=str(value["row_id"]),
            landing_cwd=str(value["landing_cwd"]),
            artifact_relpath=str(value["artifact_relpath"]),
            binding_token=str(value["binding_token"]),
            nonce=str(value["nonce"]),
            destination_state=dict(value["destination_state"]),
            predicate=PredicateSpec.from_mapping(value["predicate"]),
            predicate_closure=tuple(str(item) for item in value["predicate_closure"]),
            predicate_digest=str(value["predicate_digest"]),
            write_scope=tuple(str(item) for item in value["write_scope"]),
            integration_mode=str(value["integration_mode"]),
            destination=str(value["destination"]),
            destination_pre_state=dict(value["destination_pre_state"]),
            base_commit=(
                str(value["base_commit"]) if value.get("base_commit") is not None else None
            ),
            issued_at=float(value["issued_at"]),
        )


def write_scope_for(
    spec: session_lifecycle.ChildSpec, landing: session_lifecycle.Landing
) -> tuple[str, ...]:
    """Every location this child may write, as landing-relative paths.

    A mutating child may write its declared scope inside its own worktree.  A read-only child may
    write **nothing** in the repository: its declared scope is a *read* scope, and treating it as a
    write allowlist is what made two well-behaved read-only children in one checkout each classify
    the other a boundary violator.  Every child, of either kind, may write its own exclusive
    artifact directory.
    """
    artifacts = artifact_landing(Path(landing.cwd), spec.run_id, spec.row_id)
    relative = artifacts.resolve().relative_to(Path(landing.cwd).resolve()).as_posix()
    declared = session_lifecycle.normalize_scope(spec.scope) if spec.mutating else ()
    return tuple(dict.fromkeys((*declared, relative)))


def repository_scope_for(spec: session_lifecycle.ChildSpec) -> session_lifecycle.ChildSpec:
    """Return the spec whose ``scope`` is the child's repository *write* allowlist.

    For a read-only child that allowlist is empty, so any repository-visible change fails the
    boundary check regardless of which child made it -- and a correct read-only child makes none,
    because its artifact lands outside Git's view.
    """
    if spec.mutating:
        return spec
    return replace(spec, scope=())


def assert_landing_is_invisible_to_git(
    landing_cwd: Path,
    artifacts_dir: Path,
    *,
    git: session_lifecycle.GitLanding,
) -> None:
    """Fail closed unless the artifact landing is ignored by the repository.

    The read-only sibling repair rests on artifacts being outside the Git boundary.  That is a
    property of the repository's state, not of this code, so it is checked rather than assumed: in
    a repository that does not ignore the orchestrate state directory, artifacts would be
    repository-visible and concurrent read-only children would attribute each other's output
    again.

    "Outside the boundary" is not the same question as "matched by an ignore rule".  An operator
    who force-adds an artifact from an earlier run leaves a *tracked* path under an ignored
    directory, and every later settle of that path is then reported as a repository change -- so
    the control would fire on the orchestrator's own rename.  Refusing at issue time, before any
    child is dispatched, turns that into one actionable message instead of a child that fails
    every attempt.
    """
    relative = artifacts_dir.resolve().relative_to(landing_cwd.resolve()).as_posix()
    if not git.is_invisible_to_boundary(landing_cwd, relative):
        raise LandingNotExclusiveError(
            f"{relative} is not invisible to the repository at {landing_cwd}: it is either not "
            "ignored or already tracked. The per-child artifact landing must be outside the "
            "boundary check, otherwise concurrent children are attributed each other's artifacts "
            "and the orchestrator's own settle is read as a child write. If it is tracked, "
            f"'git rm -r --cached {relative}' clears it."
        )


def issue_receipt(
    root: Path,
    spec: session_lifecycle.ChildSpec,
    landing: session_lifecycle.Landing,
    predicate: PredicateSpec,
    *,
    artifact_name: str,
    git: session_lifecycle.GitLanding,
    nonce: str | None = None,
) -> DispatchReceipt:
    """Establish this dispatch's expected evidence identity **before** the child is dispatched.

    Everything a later comparison relies on is computed here: the run-binding token, the
    destination's pre-dispatch state, the predicate's dependency closure and its content digest,
    and the destination-integration pre-state.  None of it is read from beside the artifact later,
    because a stale record in the child's own output directory would satisfy a comparison against
    itself.

    The durable copy is **sealed** with this run's orchestrator secret (see :func:`run_secret`),
    because the register it is written to is Git-ignored and therefore writable by the child
    without any control observing it.  ``artifact_path`` is deliberately *not* written here: the
    already-shipping catch-up consumer treats a declared artifact path that does not exist as an
    operator-attention signal, and at issue time the artifact is required to be absent.  It is
    recorded once settlement has actually happened, as an absolute path, because that consumer
    resolves a relative path against the ambient checkout while a mutating child's artifact lives
    in its worktree.
    """
    landing_cwd = Path(landing.cwd).resolve()
    artifacts = artifact_landing(landing_cwd, spec.run_id, spec.row_id)
    assert_landing_is_invisible_to_git(landing_cwd, artifacts, git=git)
    artifacts.mkdir(parents=True, exist_ok=True)

    name = _safe_component(artifact_name, label="artifact_name")
    artifact_relpath = (artifacts / name).relative_to(landing_cwd).as_posix()

    scope = write_scope_for(spec, landing)
    closure = predicate_closure(landing_cwd, predicate, subject=artifact_relpath)
    assert_predicate_outside_write_scope(closure, scope)

    resolved_nonce = nonce or uuid.uuid4().hex
    token = artifact_binding_token(spec.run_id, spec.row_id, resolved_nonce)

    receipt = DispatchReceipt(
        run_id=spec.run_id,
        row_id=spec.row_id,
        landing_cwd=str(landing_cwd),
        artifact_relpath=artifact_relpath,
        binding_token=token,
        nonce=resolved_nonce,
        destination_state=_path_state(landing_cwd / artifact_relpath),
        predicate=predicate,
        predicate_closure=closure,
        predicate_digest=closure_digest(landing_cwd, predicate, closure),
        write_scope=scope,
        integration_mode=landing.integration_mode,
        destination=landing.destination,
        destination_pre_state=_integration_pre_state(landing, git=git),
        base_commit=landing.base_commit,
        issued_at=time.time(),
    )
    register_store.upsert_row(
        root,
        spec.row_id,
        {
            "run_id": spec.run_id,
            "predicate": predicate.to_mapping(),
            DISPATCH_RECEIPT_KEY: _seal(receipt.to_mapping(), run_secret(root, spec.run_id)),
            # A new dispatch supersedes any earlier attempt's settlement for this row.
            SETTLEMENT_KEY: None,
        },
    )
    return receipt


def _integration_pre_state(
    landing: session_lifecycle.Landing,
    *,
    git: session_lifecycle.GitLanding,
) -> dict[str, Any]:
    if landing.integration_mode == "branch":
        ambient = Path(landing.ambient_root or landing.cwd)
        return {"commit": git.rev_parse(ambient, landing.destination)}
    if landing.integration_mode == "path":
        ambient = Path(landing.ambient_root or landing.cwd)
        return _path_state(ambient / landing.destination)
    return {}


def artifact_instructions(receipt: DispatchReceipt) -> str:
    """The dispatch text that makes a child's output settleable and bindable.

    The child never writes the destination.  It writes the in-flight sibling, and this module
    renames.  That is why "the predicate accepts only the renamed path" is enforceable at all.
    """
    return (
        "Write your deliverable to this exact path and to no other path:\n"
        f"  {receipt.inflight_path}\n"
        "Do not create or modify:\n"
        f"  {receipt.artifact_path}\n"
        "The orchestrator renames the in-flight file into place once you stop; a deliverable "
        "written directly to the destination is rejected.\n"
        "Include this line verbatim somewhere in the deliverable, on its own line:\n"
        f"  {receipt.binding_token}\n"
    )


# --------------------------------------------------------------------------- settlement


@dataclass(frozen=True)
class Settlement:
    """The durable fact that one dispatch's artifact was renamed into place, and what it was."""

    nonce: str
    artifact_relpath: str
    artifact_path: str
    digest: str
    settled_at: float

    def to_mapping(self) -> dict[str, Any]:
        return {
            "nonce": self.nonce,
            "artifact_relpath": self.artifact_relpath,
            "artifact_path": self.artifact_path,
            "digest": self.digest,
            "settled_at": self.settled_at,
        }

    @classmethod
    def from_mapping(cls, value: Mapping[str, Any]) -> Settlement:
        return cls(
            nonce=str(value["nonce"]),
            artifact_relpath=str(value["artifact_relpath"]),
            artifact_path=str(value["artifact_path"]),
            digest=str(value["digest"]),
            settled_at=float(value["settled_at"]),
        )


def settlement_record(root: Path, receipt: DispatchReceipt) -> Settlement | None:
    """The authenticated settlement recorded for this dispatch, or ``None`` if there is none.

    Sealed with the same run secret as the receipt and for the same reason: a child that could
    plant an unauthenticated settlement record could make this module replay a settlement that
    never happened, and so accept a file the child wrote straight to the destination.
    """
    row = register_store.read_rows(root).get(receipt.row_id)
    stored = row.get(SETTLEMENT_KEY) if row is not None else None
    if not isinstance(stored, Mapping):
        return None
    payload = _unseal(stored, run_secret(root, receipt.run_id, create=False), label="settlement")
    return Settlement.from_mapping(payload)


def settle_artifact(root: Path, receipt: DispatchReceipt) -> Settlement:
    """Rename the child's in-flight file into place, once, and record that it happened.

    Three refusals on a first settlement, each of which is a real observation rather than an
    inference about how a file was produced: the destination changed during the dispatch window
    (the child wrote it directly), no in-flight file exists (the child did not follow the protocol
    at all), or the in-flight path is not a regular file (a symlink would make the rename land
    content the child chose from elsewhere).

    **Why this is idempotent, and why that is not a convenience.**  Settlement is a one-shot
    rename: after it, the in-flight file is gone and the destination is present, which is
    byte-for-byte the state a child that wrote the destination directly would leave.  Nothing on
    disk distinguishes them.  So a *second* evaluation of a correct child -- which the catch-up
    contract requires on every startup and reconnect, and which judgment-shaped work requires
    because its verifier must read the *settled* artifact -- would fail as though the child had
    cheated.  The durable settlement record is what tells the two apart, and replaying it is what
    makes a second evaluation reach the same verdict as the first instead of a false failure.

    The replay is conditional on the destination still holding exactly the bytes that were
    settled.  If it changed afterwards, this is not a replay: the evidence on disk is no longer
    the evidence that was settled, and that fails.
    """
    recorded = settlement_record(root, receipt)
    destination = receipt.artifact_path
    if recorded is not None and recorded.nonce == receipt.nonce:
        current = _path_state(destination)
        if current.get("digest") == recorded.digest:
            return recorded
        raise ArtifactError(
            f"artifact {receipt.artifact_relpath} was settled at {recorded.settled_at:.0f} with "
            f"digest {recorded.digest} and no longer matches it; the evidence on disk is not the "
            "evidence that was settled"
        )
    inflight = receipt.inflight_path
    current = _path_state(destination)
    if current != receipt.destination_state:
        raise ArtifactError(
            f"artifact destination {receipt.artifact_relpath} changed during the dispatch window; "
            "a deliverable must be written to the in-flight sibling and renamed by the "
            "orchestrator, never written directly to the destination"
        )
    if not inflight.exists() or inflight.is_symlink() or not inflight.is_file():
        raise ArtifactError(
            f"no regular in-flight artifact at {inflight.name}; the child did not produce a "
            "settleable deliverable"
        )
    os.replace(inflight, destination)
    settlement = Settlement(
        nonce=receipt.nonce,
        artifact_relpath=receipt.artifact_relpath,
        artifact_path=str(destination),
        digest=str(_path_state(destination)["digest"]),
        settled_at=time.time(),
    )
    register_store.upsert_row(
        root,
        receipt.row_id,
        {
            SETTLEMENT_KEY: _seal(
                settlement.to_mapping(), run_secret(root, receipt.run_id, create=False)
            ),
            # The catch-up consumer resolves this against the ambient checkout, so it is absolute:
            # a mutating child's artifact lives in its worktree, not under the ambient root.
            "artifact_path": settlement.artifact_path,
        },
    )
    return settlement


def assert_artifact_binding(
    path: Path,
    receipt: DispatchReceipt,
    *,
    max_bytes: int = DEFAULT_MAX_ARTIFACT_BYTES,
) -> str:
    """Require the artifact to carry this dispatch's pre-established token; return its digest."""
    size = path.stat().st_size
    if size > max_bytes:
        raise ArtifactError(
            f"artifact {receipt.artifact_relpath} is {size} bytes, above the {max_bytes}-byte "
            "binding-check bound"
        )
    data = path.read_bytes()
    text = data.decode("utf-8", errors="replace")
    if receipt.binding_token not in text:
        raise ArtifactError(
            f"artifact {receipt.artifact_relpath} does not carry this dispatch's run binding "
            f"({_describe_foreign_bindings(text)}); it is not evidence produced for run "
            f"{receipt.run_id!r} child {receipt.row_id!r} nonce {receipt.nonce!r}"
        )
    return "sha256:" + hashlib.sha256(data).hexdigest()


def _describe_foreign_bindings(text: str) -> str:
    """Name the bindings that *are* present, so a stale artifact reports as stale."""
    found = [
        f"run={match.group(1)!r} child={match.group(2)!r} nonce={match.group(3)!r}"
        for match in list(_BINDING_RE.finditer(text))[:4]
    ]
    if not found:
        return "the artifact carries no run binding at all"
    return "the artifact carries a binding for " + "; ".join(found)


# --------------------------------------------------------------------------- predicate execution


@dataclass(frozen=True)
class PredicateOutcome:
    passed: bool
    reason: str
    returncode: int | None
    output: str

    def to_mapping(self) -> dict[str, Any]:
        return {
            "passed": self.passed,
            "reason": self.reason,
            "returncode": self.returncode,
            "output": self.output,
        }


def _predicate_env(pycache_dir: Path) -> dict[str, str]:
    """Keep a well-behaved Python predicate from writing bytecode into the child's landing."""
    env = dict(os.environ)
    env["PYTHONDONTWRITEBYTECODE"] = "1"
    env["PYTHONPYCACHEPREFIX"] = str(pycache_dir)
    return env


def run_predicate(
    predicate: PredicateSpec,
    *,
    workdir: Path,
    poll_seconds: float = 0.02,
) -> PredicateOutcome:
    """Run the check inline, bounded in time and output; every abnormal end is a failure.

    Output is streamed to a temporary file rather than a pipe so the byte cap can be enforced
    while the process is still running: a predicate that produces unbounded output is killed at
    the cap rather than buffered until it exhausts memory.
    """
    with tempfile.TemporaryDirectory(prefix="orchestrate-predicate-") as scratch:
        scratch_dir = Path(scratch)
        sink_path = scratch_dir / "output"
        deadline = time.monotonic() + predicate.timeout_seconds
        with sink_path.open("wb") as sink:
            try:
                process = subprocess.Popen(  # nosec B603 -- fixed argv sequence, shell never used
                    list(predicate.argv),
                    cwd=str(workdir),
                    stdout=sink,
                    stderr=subprocess.STDOUT,
                    env=_predicate_env(scratch_dir / "pycache"),
                )
            except (OSError, subprocess.SubprocessError) as exc:
                return PredicateOutcome(False, "predicate_error", None, f"{exc}")
            reason = ""
            while True:
                returncode = process.poll()
                if returncode is not None:
                    break
                if sink_path.stat().st_size > predicate.max_output_bytes:
                    reason = "predicate_output_limit"
                elif time.monotonic() >= deadline:
                    reason = "predicate_timeout"
                if reason:
                    process.kill()
                    process.wait()
                    break
                time.sleep(poll_seconds)
        output = _read_tail(sink_path, predicate.max_output_bytes)
        if reason:
            return PredicateOutcome(False, reason, None, output)
        if sink_path.stat().st_size > predicate.max_output_bytes:
            # A process that exits between two polls can still have breached the cap.
            return PredicateOutcome(False, "predicate_output_limit", process.returncode, output)
        if process.returncode != 0:
            return PredicateOutcome(False, "predicate_failed", process.returncode, output)
        return PredicateOutcome(True, "passed", 0, output)


def _read_tail(path: Path, limit: int) -> str:
    size = path.stat().st_size
    with path.open("rb") as stream:
        if size > limit:
            stream.seek(size - limit)
        return stream.read(limit).decode("utf-8", errors="replace")


# --------------------------------------------------------------------------- integration


def verify_integration(
    receipt: DispatchReceipt,
    landing: session_lifecycle.Landing,
    *,
    git: session_lifecycle.GitLanding,
) -> str:
    """Require the recorded destination to have actually moved before a child may be reaped.

    ``branch``: the destination branch must exist and its tip must differ from the commit the
    branch pointed at when the receipt was issued.  ``path``: the destination path's content must
    differ from its pre-dispatch state.  ``none``: read-only work integrates nowhere and there is
    nothing to verify -- that is the whole reason the mode exists, and it is stated rather than
    silently skipped.
    """
    mode = receipt.integration_mode
    if mode == "none":
        return "read-only artifact; integration mode 'none' has no destination to verify"
    ambient = Path(landing.ambient_root or landing.cwd)
    if mode == "branch":
        tip = git.rev_parse(ambient, receipt.destination)
        if tip is None:
            raise CompletionError(
                f"integration destination branch {receipt.destination!r} does not exist"
            )
        before = receipt.destination_pre_state.get("commit")
        if tip == before:
            raise CompletionError(
                f"integration destination branch {receipt.destination!r} is unchanged at {tip}; "
                "the child's work has not landed and reaping would discard it"
            )
        return f"branch {receipt.destination} advanced to {tip}"
    if mode == "path":
        current = _path_state(ambient / receipt.destination)
        if current == receipt.destination_pre_state:
            raise CompletionError(
                f"integration destination path {receipt.destination!r} is unchanged; the child's "
                "work has not landed and reaping would discard it"
            )
        return f"path {receipt.destination} changed"
    raise CompletionError(f"unsupported integration mode {mode!r}")


# --------------------------------------------------------------------------- depth sample


def is_judgment_shaped(work_shape: str) -> bool:
    """Classify through U1's authoritative vocabulary, including its role-tier aliases."""
    canonical = tier_resolver.ROLE_TIER_ALIASES.get(work_shape, work_shape)
    return canonical in JUDGMENT_WORK_SHAPES


@dataclass(frozen=True)
class SampledClaim:
    claim: str
    evidence_location: str
    disposition: str

    def __post_init__(self) -> None:
        if not self.claim.strip():
            raise DepthSampleError("a sampled claim must name the claim it sampled")
        if not self.evidence_location.strip():
            raise DepthSampleError(
                f"sampled claim {self.claim!r} must record where its evidence was checked"
            )
        if self.disposition not in DEPTH_DISPOSITIONS:
            raise DepthSampleError(
                f"disposition {self.disposition!r} is not one of {DEPTH_DISPOSITIONS}"
            )

    def to_mapping(self) -> dict[str, str]:
        return {
            "claim": self.claim,
            "evidence_location": self.evidence_location,
            "disposition": self.disposition,
        }


@dataclass(frozen=True)
class DepthSample:
    """One independent verifier's blind read of a judgment-shaped child's artifact."""

    verifier_row_id: str
    verifier_vendor: str
    verifier_model: str
    artifact_digest: str
    claims: tuple[SampledClaim, ...]

    def to_mapping(self) -> dict[str, Any]:
        return {
            "verifier_row_id": self.verifier_row_id,
            "verifier_vendor": self.verifier_vendor,
            "verifier_model": self.verifier_model,
            "artifact_digest": self.artifact_digest,
            "claims": [claim.to_mapping() for claim in self.claims],
        }

    @classmethod
    def from_mapping(cls, value: Mapping[str, Any]) -> DepthSample:
        """Parse an external depth mapping, raising :class:`DepthSampleError` for anything else.

        Every rejection is this one exception type on purpose.  This is the boundary where data
        that came from *outside* the orchestrator arrives, and the caller converts a
        ``DepthSampleError`` into a recorded ``depth_sample_invalid`` verdict.  A ``KeyError`` or a
        ``TypeError`` escaping here would instead take down the evaluation before anything is
        written, leaving a register that still shows the child working -- a control that raises
        instead of recording is a fail-open one level up.

        Claim entries are validated rather than filtered.  Silently skipping a non-mapping entry
        turns "one supported claim plus garbage" into a clean one-claim sample that can verify.
        """
        if not isinstance(value, Mapping):
            raise DepthSampleError("a depth sample must be a JSON object")
        claims = value.get("claims")
        if not isinstance(claims, Sequence) or isinstance(claims, str):
            raise DepthSampleError("a depth sample must carry a claims array")
        fields: dict[str, str] = {}
        for key in ("verifier_row_id", "verifier_vendor", "verifier_model", "artifact_digest"):
            item = value.get(key)
            if not isinstance(item, str) or not item.strip():
                raise DepthSampleError(f"a depth sample must carry a non-empty {key!r}")
            fields[key] = item
        parsed: list[SampledClaim] = []
        for index, item in enumerate(claims):
            if not isinstance(item, Mapping):
                raise DepthSampleError(f"sampled claim {index} is not a JSON object")
            missing = [
                key
                for key in ("claim", "evidence_location", "disposition")
                if not isinstance(item.get(key), str)
            ]
            if missing:
                raise DepthSampleError(f"sampled claim {index} is missing {sorted(missing)}")
            parsed.append(
                SampledClaim(
                    str(item["claim"]), str(item["evidence_location"]), str(item["disposition"])
                )
            )
        return cls(
            verifier_row_id=fields["verifier_row_id"],
            verifier_vendor=fields["verifier_vendor"],
            verifier_model=fields["verifier_model"],
            artifact_digest=fields["artifact_digest"],
            claims=tuple(parsed),
        )

    def validate(
        self,
        *,
        root: Path,
        child_row_id: str,
        run_id: str,
        artifact_digest: str,
    ) -> None:
        """Check what a record *can* establish: independence, binding, and completeness.

        Independence is enforced against the register, not against the sample.  A
        ``verifier_row_id`` that is merely a non-empty string different from the child's is not a
        session -- ``"verifier-that-does-not-exist"`` satisfies that test -- and "an independent
        verifier session" is the requirement.  So the named row must exist, must belong to this
        run, must have got far enough to actually run, and must be the vendor and model the sample
        claims it was.  The last check is what stops a sample from attributing a read to a
        different, more credible session than the one that performed it.

        Binding to this artifact is enforced by digest, so a sample recorded against some other
        document cannot be presented as a read of this one.

        Blindness -- that the verifier saw the artifact and not the child's own account of it --
        is a property of how the verifier was dispatched and is *not* provable from this record.
        Neither is vendor diversity between child and verifier: this module does not require them
        to differ.  Both are dispatch-contract obligations, owned by ``references/predicates.md``.
        """
        if not self.verifier_row_id or self.verifier_row_id == child_row_id:
            raise DepthSampleError(
                "a depth sample must come from a verifier session other than the child itself; "
                f"got {self.verifier_row_id!r} for child {child_row_id!r}"
            )
        if self.artifact_digest != artifact_digest:
            raise DepthSampleError(
                "the depth sample is recorded against a different artifact "
                f"({self.artifact_digest} != {artifact_digest}); it is not a read of this "
                "dispatch's evidence"
            )
        if not self.claims:
            raise DepthSampleError("a depth sample must record at least one sampled claim")
        self._assert_verifier_session(root, run_id=run_id)

    def _assert_verifier_session(self, root: Path, *, run_id: str) -> None:
        row = register_store.read_rows(root).get(self.verifier_row_id)
        if row is None:
            raise DepthSampleError(
                f"the depth sample names verifier {self.verifier_row_id!r}, which has no row in "
                "the register; an independent verifier session is a session that was dispatched, "
                "not a string in a mapping"
            )
        if row.get("run_id") != run_id:
            raise DepthSampleError(
                f"verifier {self.verifier_row_id!r} belongs to run {row.get('run_id')!r}, not to "
                f"this child's run {run_id!r}"
            )
        phase = row.get("phase")
        if phase in (None, "planned", "launching"):
            raise DepthSampleError(
                f"verifier {self.verifier_row_id!r} never reached a running session "
                f"(phase {phase!r}); it cannot have read anything"
            )
        for column, declared in (
            ("vendor", self.verifier_vendor),
            ("model", self.verifier_model),
        ):
            recorded = row.get(column)
            if not isinstance(recorded, str) or not recorded:
                raise DepthSampleError(
                    f"verifier {self.verifier_row_id!r} has no recorded {column}; the sample's "
                    "claim about who read the artifact cannot be checked"
                )
            if recorded != declared:
                raise DepthSampleError(
                    f"the depth sample says verifier {self.verifier_row_id!r} is {column} "
                    f"{declared!r}, but the register records {recorded!r}"
                )


# --------------------------------------------------------------------------- evaluation


@dataclass(frozen=True)
class CompletionResult:
    row_id: str
    verified: bool
    reason: str
    detail: str
    predicate: PredicateOutcome | None = None
    scope: session_lifecycle.ScopeCheck | None = None
    artifact_digest: str | None = None
    artifact_path: str | None = None
    integration: str | None = None
    depth_sample: DepthSample | None = None

    def to_mapping(self) -> dict[str, Any]:
        return {
            "result": "verified" if self.verified else "failed",
            "reason": self.reason,
            "detail": self.detail,
            "predicate": self.predicate.to_mapping() if self.predicate is not None else None,
            "artifact_digest": self.artifact_digest,
            "artifact_path": self.artifact_path,
            "integration": self.integration,
            # The verifier's identity, the claims it sampled, where it checked each one, and how
            # it disposed of them. Without this a child that was genuinely sampled and one whose
            # sample certified nothing are the same green row, and the pass becomes its own
            # evidence -- which is the exact failure this unit exists to prevent.
            "depth_sample": self.depth_sample.to_mapping() if self.depth_sample else None,
            "at": time.time(),
        }


def _record(root: Path, row_id: str, result: CompletionResult) -> CompletionResult:
    """Write the durable verdict, and keep ``phase`` honest about it.

    The verdict lives in its own ``completion`` key rather than in ``observed_state``.
    ``observed_state`` is owned by the liveness detectors: the subscriber's snapshot catch-up
    rewrites it for every row with a live pane, so a failure recorded only there is erased the
    next time catch-up runs while the child's pane is still open.

    The invariant this function maintains is: **a row's phase is ``verified`` if and only if its
    latest completion verdict is a pass.**  Both halves matter, and the second one is not
    optional now that re-evaluation is a specified behaviour rather than a hypothetical -- the
    catch-up contract re-evaluates run-bound artifacts and predicates on every startup and
    reconnect.  A row that passed once and fails its re-evaluation would otherwise end with
    ``phase="verified"`` and ``completion.result="failed"``, and U4's reap gate reads the phase:
    the contradiction would be consumed as a pass.

    A failing verdict therefore leaves the row at ``working`` -- by leaving the phase untouched
    for a first evaluation, or by demoting it from ``verified`` for a re-evaluation.  Both are the
    same rule, and neither invents a phase: ``PHASES`` is a closed, operator-approved vocabulary
    with no member meaning "evaluated and failed", and "evaluated and failed" is already
    representable as ``phase="working"`` plus a recorded failure, which is what
    :func:`is_working_not_failed` and :func:`failed_rows` read.  A ``reaped`` row is past this
    question and is left alone.

    The ``artifact_path`` *column* is deliberately not written here.  It has exactly one owner --
    :func:`settle_artifact`, the moment the fact becomes true -- because two writers of one column
    is how a column ends up meaning whatever the last writer thought it meant.  The path is still
    part of this verdict's own record, inside the ``completion`` mapping.
    """
    fields: dict[str, Any] = {"completion": result.to_mapping()}
    if result.verified:
        fields["phase"] = "verified"
        fields["expected_state"] = "verified"
    elif register_store.read_rows(root).get(row_id, {}).get("phase") == "verified":
        fields["phase"] = "working"
        fields["expected_state"] = "working"
    register_store.upsert_row(root, row_id, fields)
    return result


def evaluate_completion(
    root: Path,
    spec: session_lifecycle.ChildSpec,
    landing: session_lifecycle.Landing,
    changed_paths_baseline: session_lifecycle.ChangedPathsBaseline,
    receipt: DispatchReceipt,
    *,
    git: session_lifecycle.GitLanding,
    depth_sample: DepthSample | Mapping[str, Any] | None = None,
) -> CompletionResult:
    """Decide whether one child reaches ``verified``, and record why either way.

    Safe to call more than once for one dispatch, which is what makes both the restart path and
    judgment-shaped work reachable.  Settlement replays from its durable record instead of
    consuming the in-flight file a second time (see :func:`settle_artifact`), so the sequence for
    judgment work is: evaluate once and get ``depth_sample_missing`` with the artifact now settled
    at a recorded digest; dispatch an independent verifier against that settled path; evaluate
    again with its sample.  The second call re-runs the mechanical controls rather than trusting
    the first call's verdict, so the answer is a fresh one, not a cached one.
    """
    landing_cwd = Path(landing.cwd)
    state: dict[str, Any] = {}

    def fail(reason: str, detail: str, **fields: Any) -> CompletionResult:
        return _record(
            root,
            spec.row_id,
            CompletionResult(spec.row_id, False, reason, detail, **{**state, **fields}),
        )

    # The receipt, the specification, the landing and the baseline arrive as four independent
    # arguments and every outcome is recorded under the specification's row. Nothing else in this
    # function would notice if they described different children, so a correctly bound artifact
    # for one child could verify another child's row.
    mismatches = [
        f"{label}: spec {mine!r} != receipt {theirs!r}"
        for label, mine, theirs in (
            ("run_id", spec.run_id, receipt.run_id),
            ("row_id", spec.row_id, receipt.row_id),
            ("landing", str(landing_cwd.resolve()), str(Path(receipt.landing_cwd).resolve())),
        )
        if mine != theirs
    ]
    if mismatches:
        return fail(
            "receipt_mismatch",
            "the dispatch receipt does not belong to the child being evaluated ("
            + "; ".join(mismatches)
            + "); evidence produced for one dispatch cannot verify another",
        )

    current_digest = closure_digest(landing_cwd, receipt.predicate, receipt.predicate_closure)
    if current_digest != receipt.predicate_digest:
        return fail(
            "predicate_tampered",
            "the predicate's dependency closure changed between dispatch and evaluation; "
            f"expected {receipt.predicate_digest}, found {current_digest}",
        )

    try:
        settlement = settle_artifact(root, receipt)
    except (ArtifactError, ReceiptAuthenticationError) as exc:
        # An unauthenticated settlement record is recorded as a refusal rather than raised. A
        # control that raises instead of recording leaves the register showing a working child
        # with no verdict, which is a fail-open one level up.
        return fail("artifact_unsettled", str(exc))
    artifact = Path(settlement.artifact_path)
    state["artifact_path"] = settlement.artifact_path

    try:
        state["artifact_digest"] = assert_artifact_binding(artifact, receipt)
    except ArtifactError as exc:
        return fail("artifact_binding", str(exc))
    artifact_digest = str(state["artifact_digest"])

    artifacts_dir = artifact_landing(landing_cwd, receipt.run_id, receipt.row_id)
    observer_baseline = git.changed_paths_baseline(
        landing_cwd,
        base_commit=landing.base_commit,
        ambient_root=landing.ambient_root,
    )
    artifacts_before = _artifact_fingerprints(artifacts_dir)
    outcome = run_predicate(receipt.predicate, workdir=landing_cwd)
    state["predicate"] = outcome
    disturbed = _predicate_side_effects(
        landing, observer_baseline, artifacts_before, artifacts_dir=artifacts_dir, git=git
    )
    if disturbed:
        return fail(
            "predicate_side_effect",
            "the predicate changed the child's landing or its evidence while evaluating it, so "
            "what is on disk is no longer what was bound: " + ", ".join(sorted(disturbed)),
        )

    try:
        state["scope"] = session_lifecycle.check_completion_scope(
            repository_scope_for(spec),
            landing,
            changed_paths_baseline,
            predicate_passed=outcome.passed,
            git=git,
        )
    except session_lifecycle.ScopeViolationError as exc:
        return fail("scope_violation", str(exc))

    if not outcome.passed:
        return fail(
            outcome.reason,
            f"predicate {list(receipt.predicate.argv)} did not pass: {outcome.reason}",
        )

    try:
        state["integration"] = verify_integration(receipt, landing, git=git)
    except CompletionError as exc:
        return fail("integration_unverified", str(exc))

    sample, depth_failure = _depth_verdict(
        root, spec, depth_sample, artifact_digest=artifact_digest
    )
    state["depth_sample"] = sample
    if depth_failure is not None:
        return fail(*depth_failure)

    return _record(
        root,
        spec.row_id,
        CompletionResult(
            spec.row_id,
            True,
            "verified",
            f"settled, run-bound artifact {receipt.artifact_relpath} passed "
            f"{list(receipt.predicate.argv)}; {state['integration']}",
            **state,
        ),
    )


def _artifact_fingerprints(artifacts_dir: Path) -> tuple[tuple[str, str], ...]:
    """Digest every file in the child's exclusive artifact directory.

    The Git snapshot cannot see this directory at all -- it is *required* to be invisible to the
    boundary, which is the entire basis of the read-only sibling repair -- so the observer whose
    job is "the predicate must not disturb the evidence" has to observe the evidence directly or
    it is not observing the evidence at all.  The whole directory rather than the one artifact,
    because a predicate that rewrites the in-flight sibling of the next dispatch is the same
    defect wearing a different filename.
    """
    if not artifacts_dir.is_dir():
        return ()
    entries: list[tuple[str, str]] = []
    for path in sorted(artifacts_dir.rglob("*")):
        relative = path.relative_to(artifacts_dir).as_posix()
        if path.is_symlink():
            entries.append((relative, "symlink:" + os.readlink(path)))
        elif path.is_file():
            entries.append((relative, str(_path_state(path).get("digest"))))
    return tuple(entries)


def _predicate_side_effects(
    landing: session_lifecycle.Landing,
    observer_baseline: session_lifecycle.ChangedPathsBaseline,
    artifacts_before: Sequence[tuple[str, str]],
    *,
    artifacts_dir: Path,
    git: session_lifecycle.GitLanding,
) -> set[str]:
    """Everything the predicate itself touched: repository-visible paths, and the evidence.

    Compared against snapshots taken immediately before the predicate ran, so anything reported
    here was authored by the check and not by the child.  Three surfaces, because the check can
    reach all three: the child's landing, the ambient checkout (a mutating child's predicate runs
    in its worktree while the ambient tree is observed separately), and the Git-invisible artifact
    directory.

    What is still **not** observed: Git-ignored paths outside the artifact directory, including
    ``.orchestrate/register.json`` itself.  A predicate that rewrites the register is not caught
    here -- it is caught by the register's records being authenticated, which is a different
    control with a different mechanism, stated in ``references/predicates.md``.
    """
    after = git.changed_paths_baseline(
        Path(landing.cwd),
        base_commit=landing.base_commit,
        ambient_root=landing.ambient_root,
    )
    prefix = artifacts_dir.name
    artifact_changes = {
        f"{prefix}/{name}"
        for name in _differences(artifacts_before, _artifact_fingerprints(artifacts_dir))
    }
    return (
        _differences(observer_baseline.fingerprints, after.fingerprints)
        | _differences(observer_baseline.ambient_fingerprints, after.ambient_fingerprints)
        | artifact_changes
    )


def _differences(before: Sequence[tuple[str, str]], after: Sequence[tuple[str, str]]) -> set[str]:
    before_map = dict(before)
    after_map = dict(after)
    return {
        path
        for path in set(before_map) | set(after_map)
        if before_map.get(path) != after_map.get(path)
    }


def _depth_verdict(
    root: Path,
    spec: session_lifecycle.ChildSpec,
    depth_sample: DepthSample | Mapping[str, Any] | None,
    *,
    artifact_digest: str,
) -> tuple[DepthSample | None, tuple[str, str] | None]:
    """Judgment-shaped work cannot reach verified on mechanical coverage alone.

    Returns the parsed sample -- so the caller can put it on the record whichever way the verdict
    goes -- alongside the failure, if any.  Every parse and validation error is converted into a
    recorded failure here rather than raised, because the caller is the only thing that writes to
    the register: an exception escaping this function leaves a child that looks like it is still
    working when in fact it was evaluated and refused.
    """
    if not is_judgment_shaped(spec.work_shape):
        return None, None
    if depth_sample is None:
        return None, (
            "depth_sample_missing",
            f"work shape {spec.work_shape!r} is judgment-shaped, so a passing mechanical "
            "predicate is not sufficient; an independent verifier's depth sample is required",
        )
    try:
        sample = (
            depth_sample
            if isinstance(depth_sample, DepthSample)
            else DepthSample.from_mapping(depth_sample)
        )
    except DepthSampleError as exc:
        return None, ("depth_sample_invalid", str(exc))
    try:
        sample.validate(
            root=root,
            child_row_id=spec.row_id,
            run_id=spec.run_id,
            artifact_digest=artifact_digest,
        )
    except DepthSampleError as exc:
        return sample, ("depth_sample_invalid", str(exc))
    unsupported = [claim for claim in sample.claims if claim.disposition == "unsupported"]
    if unsupported:
        return sample, (
            "depth_sample_unsupported",
            "the independent verifier could not support "
            + "; ".join(f"{claim.claim!r} at {claim.evidence_location}" for claim in unsupported),
        )
    if not any(claim.disposition == "supported" for claim in sample.claims):
        # A sample whose every claim came back "inconclusive" established nothing. Treating the
        # absence of a refutation as a confirmation is how an independent read becomes a
        # formality, and it is indistinguishable downstream from a real one.
        return sample, (
            "depth_sample_inconclusive",
            f"the independent verifier sampled {len(sample.claims)} claim(s) and could support "
            "none of them; a sample that established nothing does not certify judgment work",
        )
    return sample, None


def read_receipt(root: Path, row_id: str) -> DispatchReceipt:
    """Load and authenticate the receipt this dispatch established.

    This is the only path a restarted orchestrator has to the expected evidence identity, and it
    reads that identity out of a Git-ignored file the child can write.  The authentication is
    therefore not a formality: without it a child plants whatever binding token or predicate it
    can already satisfy and then satisfies it.  Failing here is a refusal to complete, which is
    the correct outcome -- a receipt that cannot be authenticated establishes nothing, and a child
    with no establishable expected identity has no way to be verified.
    """
    row = register_store.read_rows(root).get(row_id)
    if row is None:
        raise CompletionError(f"unknown child row {row_id!r}")
    stored = row.get(DISPATCH_RECEIPT_KEY)
    if not isinstance(stored, Mapping):
        raise CompletionError(
            f"child {row_id!r} has no dispatch receipt; it was never bound to a dispatch and "
            "cannot be completed"
        )
    claimed_run = stored.get("run_id")
    if not isinstance(claimed_run, str) or not claimed_run:
        raise ReceiptAuthenticationError(
            f"the dispatch receipt stored for {row_id!r} names no run and cannot be authenticated"
        )
    # The run_id comes from the untrusted record, but naming a different run only changes *which*
    # secret the digest must have been produced under -- never whether one is needed. ``create``
    # is off so a record naming a run this host never issued fails instead of minting a key.
    secret = run_secret(root, claimed_run, create=False)
    return DispatchReceipt.from_mapping(_unseal(stored, secret, label="dispatch receipt"))


def completion_record(root: Path, row_id: str) -> dict[str, Any] | None:
    """The operator-facing verdict for one row, or ``None`` when it has not been evaluated."""
    row = register_store.read_rows(root).get(row_id)
    if row is None:
        return None
    record = row.get("completion")
    return dict(record) if isinstance(record, Mapping) else None


def is_working_not_failed(root: Path, row_id: str) -> bool:
    """True when a row is still working rather than carrying a recorded failure.

    ``PHASES`` has no member for "evaluated and failed", so this is how the operator's view keeps
    the two apart without inventing one.
    """
    record = completion_record(root, row_id)
    return record is None or record.get("result") != "failed"


def failed_rows(root: Path, *, run_id: str | None = None) -> dict[str, dict[str, Any]]:
    """Every row whose recorded verdict is a failure -- the operator's "what stalled" view."""
    rows = register_store.read_rows(root, run_id=run_id)
    failed: dict[str, dict[str, Any]] = {}
    for row_id, row in rows.items():
        record = row.get("completion")
        if isinstance(record, Mapping) and record.get("result") == "failed":
            failed[row_id] = dict(record)
    return failed
