#!/usr/bin/env python3
"""Render Saga documentation visuals from the curated docs model."""

from __future__ import annotations

import argparse
import html
import sys
import textwrap
from pathlib import Path
from typing import Any

import yaml

REPO_ROOT = Path(__file__).resolve().parents[3]
MODEL_PATH = REPO_ROOT / "plugins" / "saga" / "docs" / "model" / "saga-docs-model.yaml"

CANVAS_W = 1600
CANVAS_H = 900

COLORS = {
    "ink": "#17202a",
    "muted": "#52616f",
    "paper": "#fbfcfd",
    "line": "#c7d0d8",
    "teal": "#0f7c80",
    "blue": "#2f6fbd",
    "green": "#3f7d4d",
    "amber": "#b7791f",
    "rose": "#b24a5a",
    "violet": "#6b5fb5",
    "panel": "#ffffff",
}


def _load_model(path: Path = MODEL_PATH) -> dict[str, Any]:
    data = yaml.safe_load(path.read_text(encoding="utf-8"))
    if not isinstance(data, dict):
        raise ValueError(f"model must be a mapping: {path}")
    return data


def _esc(value: object) -> str:
    return html.escape(str(value), quote=True)


def _wrap(value: str, width: int) -> list[str]:
    return textwrap.wrap(value, width=width, break_long_words=False) or [""]


def _svg_open(title: str, desc: str) -> list[str]:
    return [
        f'<svg xmlns="http://www.w3.org/2000/svg" width="{CANVAS_W}" height="{CANVAS_H}" '
        f'viewBox="0 0 {CANVAS_W} {CANVAS_H}" role="img" aria-labelledby="title desc">',
        f'  <title id="title">{_esc(title)}</title>',
        f'  <desc id="desc">{_esc(desc)}</desc>',
        "  <!-- Generated by plugins/saga/scripts/render_docs_visuals.py from "
        "plugins/saga/docs/model/saga-docs-model.yaml. Do not edit by hand. -->",
        f'  <rect width="{CANVAS_W}" height="{CANVAS_H}" fill="{COLORS["paper"]}"/>',
        "  <style>",
        "    .title { font: 700 42px -apple-system, BlinkMacSystemFont, Segoe UI, sans-serif; }",
        "    .subtitle { font: 500 22px -apple-system, BlinkMacSystemFont, Segoe UI, sans-serif; }",
        "    .label { font: 700 20px -apple-system, BlinkMacSystemFont, Segoe UI, sans-serif; }",
        "    .body { font: 500 17px -apple-system, BlinkMacSystemFont, Segoe UI, sans-serif; }",
        "    .small { font: 500 14px -apple-system, BlinkMacSystemFont, Segoe UI, sans-serif; }",
        "  </style>",
    ]


def _svg_close(parts: list[str]) -> str:
    parts.append("</svg>")
    return "\n".join(parts) + "\n"


def _text(
    parts: list[str],
    x: int,
    y: int,
    text: str,
    *,
    cls: str = "body",
    fill: str = "ink",
    max_chars: int | None = None,
    line_height: int = 22,
) -> None:
    lines = _wrap(text, max_chars) if max_chars else [text]
    parts.append(f'  <text x="{x}" y="{y}" class="{cls}" fill="{COLORS[fill]}">')
    for index, line in enumerate(lines):
        dy = 0 if index == 0 else line_height
        parts.append(f'    <tspan x="{x}" dy="{dy}">{_esc(line)}</tspan>')
    parts.append("  </text>")


def _box(
    parts: list[str],
    x: int,
    y: int,
    width: int,
    height: int,
    *,
    fill: str = "panel",
    stroke: str = "line",
    radius: int = 8,
) -> None:
    parts.append(
        f'  <rect x="{x}" y="{y}" width="{width}" height="{height}" rx="{radius}" '
        f'fill="{COLORS[fill]}" stroke="{COLORS[stroke]}" stroke-width="2"/>'
    )


def _line(parts: list[str], x1: int, y1: int, x2: int, y2: int, *, color: str = "line") -> None:
    parts.append(
        f'  <line x1="{x1}" y1="{y1}" x2="{x2}" y2="{y2}" '
        f'stroke="{COLORS[color]}" stroke-width="3" stroke-linecap="round"/>'
    )


def _pill(parts: list[str], x: int, y: int, label: str, *, fill: str) -> None:
    width = max(96, 12 * len(label) + 22)
    parts.append(
        f'  <rect x="{x}" y="{y}" width="{width}" height="34" rx="17" fill="{COLORS[fill]}"/>'
    )
    _text(parts, x + 14, y + 23, label, cls="small", fill="paper")


def render_lifecycle_atlas(model: dict[str, Any]) -> str:
    parts = _svg_open(
        "Saga Lifecycle Atlas",
        "Main Saga lifecycle, gates, off-chain routes, and destination horizon.",
    )
    _text(parts, 70, 80, "Saga Lifecycle Atlas", cls="title")
    _text(
        parts,
        70,
        118,
        "The spine moves from frame and requirements to reviewed plan, work, PR gate, QA, and learning.",
        cls="subtitle",
        fill="muted",
    )

    chain = [
        ("Frame", "/office-hours", "Find the problem frame", "teal"),
        ("Idea", "/ideate", "Generate survivor ideas", "blue"),
        ("Requirements", "/brainstorm / /spec", "Settle the WHAT", "green"),
        ("Plan", "/plan", "Settle the HOW", "amber"),
        ("Readiness", "/doc-review", "P0/P1 gate before work", "rose"),
        ("Work", "/work", "Build, test, PR loop", "violet"),
        ("Acceptance", "/qa", "Evidence-backed verdict", "teal"),
    ]
    start_x = 70
    y = 205
    card_w = 190
    gap = 25
    for index, (label, command, body, color) in enumerate(chain):
        x = start_x + index * (card_w + gap)
        _box(parts, x, y, card_w, 150)
        _pill(parts, x + 18, y + 18, label, fill=color)
        _text(parts, x + 18, y + 82, command, cls="label", max_chars=15, line_height=22)
        _text(parts, x + 18, y + 120, body, max_chars=18, fill="muted")
        if index < len(chain) - 1:
            _line(parts, x + card_w, y + 76, x + card_w + gap, y + 76, color=color)

    _box(parts, 70, 435, 1460, 170)
    _text(parts, 100, 480, "Off-chain and review loops", cls="label")
    off_chain = [
        ("/strategy", "Records direction"),
        ("/founder-review", "Challenges ambition/scope"),
        ("/investigate", "Finds root cause"),
        ("/optimize", "Runs metric experiments"),
        ("/handoff", "Builds issue envelope"),
        ("/retro", "Captures learning"),
        ("/resume", "Forensic reconstruction"),
        ("/loop", "Routes and re-enters"),
    ]
    for index, (command, body) in enumerate(off_chain):
        col = index % 4
        row = index // 4
        x = 100 + col * 350
        item_y = 520 + row * 40
        _text(parts, x, item_y, command, cls="label", fill="blue")
        _text(parts, x + 190, item_y, body, max_chars=18, line_height=18, fill="muted")

    _box(parts, 70, 650, 1460, 140, fill="panel")
    _text(parts, 100, 694, "Destination horizon", cls="label")
    for index, (destination, info) in enumerate(model["destinations"].items()):
        x = 360 + index * 285
        _pill(parts, x, 670, destination, fill=("green" if destination == "merge" else "blue"))
        _text(parts, x, 724, info["horizon"], max_chars=25, fill="muted", line_height=20)

    _text(
        parts,
        70,
        840,
        "Hard gate: unresolved /doc-review P0/P1 blocks /work. PR and merge remain confirmed /work actions.",
        cls="small",
        fill="muted",
    )
    return _svg_close(parts)


def render_state_readiness_ladder(model: dict[str, Any]) -> str:
    parts = _svg_open(
        "State and Readiness Ladder",
        "Stored saga state axes beside derived handoff maturity.",
    )
    _text(parts, 70, 80, "State and Readiness Ladder", cls="title")
    _text(
        parts,
        70,
        118,
        "Stored state answers where the thread is; readiness is derived at handoff.",
        cls="subtitle",
        fill="muted",
    )

    _box(parts, 70, 180, 620, 560)
    _text(parts, 110, 230, "Stored saga axes", cls="label")
    axis_y = 285
    for axis, data in model["state_axes"].items():
        _box(parts, 110, axis_y, 520, 105)
        _text(parts, 140, axis_y + 38, axis, cls="label", fill="blue")
        _text(parts, 140, axis_y + 68, ", ".join(data["values"]), max_chars=46, fill="muted")
        axis_y += 135

    _box(parts, 760, 180, 770, 560)
    _text(parts, 800, 230, "Derived maturity passport", cls="label")
    maturity_rows = [
        ("docs/ideation/", "idea-ready", "/plan"),
        ("docs/brainstorms/ + docs/specs/", "requirements-ready", "/plan"),
        ("docs/plans/ + docs/reviews/", "plan-ready", "/work"),
        ("docs/work-sessions/ + branch refs", "resume-ready", "/work"),
    ]
    y = 285
    for source, maturity, consumer in maturity_rows:
        _box(parts, 800, y, 660, 82)
        _text(parts, 830, y + 34, source, fill="muted")
        _text(parts, 1115, y + 34, maturity, cls="label", fill="green")
        _text(parts, 1370, y + 34, consumer, cls="label", fill="blue")
        y += 105

    _box(parts, 760, 760, 770, 70, fill="panel", stroke="amber")
    _text(
        parts,
        800,
        804,
        "Rule: maturity is derived, never stored in saga frontmatter.",
        cls="label",
        fill="amber",
    )
    return _svg_close(parts)


def render_command_matrix(model: dict[str, Any]) -> str:
    parts = _svg_open("Command Matrix", "Saga command ownership by phase and state behavior.")
    _text(parts, 70, 80, "Command Matrix", cls="title")
    _text(
        parts,
        70,
        118,
        "17 routable commands plus /ceo-review as the /founder-review alias.",
        cls="subtitle",
        fill="muted",
    )

    groups = [
        ("Think", ["office-hours", "ideate", "brainstorm", "spec", "strategy"], "teal"),
        ("Plan/Review", ["plan", "doc-review", "founder-review", "code-review"], "blue"),
        ("Work/QA", ["work", "qa", "resume", "loop"], "green"),
        ("Off-chain/Route", ["investigate", "optimize", "handoff", "retro"], "amber"),
    ]
    state_tags = {
        "office-hours": ("no-write", "teal"),
        "ideate": ("idea-ready", "blue"),
        "brainstorm": ("req-ready", "green"),
        "spec": ("off-chain", "amber"),
        "strategy": ("off-chain", "amber"),
        "plan": ("plan tick", "green"),
        "doc-review": ("readiness", "rose"),
        "founder-review": ("scope", "violet"),
        "code-review": ("PR gate", "rose"),
        "work": ("writer", "green"),
        "qa": ("QA gate", "teal"),
        "resume": ("re-entry", "blue"),
        "loop": ("router", "violet"),
        "investigate": ("read-only", "amber"),
        "optimize": ("optimize", "amber"),
        "handoff": ("envelope", "blue"),
        "retro": ("terminal", "teal"),
    }
    x = 70
    for title, commands, color in groups:
        _box(parts, x, 175, 350, 565)
        _pill(parts, x + 24, 205, title, fill=color)
        y = 275
        for command_id in commands:
            card = model["commands"][command_id]
            tag, tag_color = state_tags[command_id]
            _text(parts, x + 28, y, card["command"], cls="label", fill="blue")
            _text(
                parts,
                x + 28,
                y + 28,
                card["lifecycle_role"],
                max_chars=28,
                fill="muted",
                line_height=18,
            )
            _pill(parts, x + 205, y - 22, tag, fill=tag_color)
            y += 94
        x += 370

    _box(parts, 70, 780, 1460, 55, fill="panel")
    _text(
        parts,
        100,
        816,
        "/ceo-review -> /founder-review alias. Count it as a command file, not a lifecycle node.",
        cls="label",
        fill="rose",
    )
    return _svg_close(parts)


def render_ownership_boundary_map(model: dict[str, Any]) -> str:
    parts = _svg_open(
        "Ownership Boundary Map",
        "Saga ownership beside mission-control, deploy, and team-execution.",
    )
    _text(parts, 70, 80, "Ownership Boundary Map", cls="title")
    _text(
        parts,
        70,
        118,
        "Saga links to adjacent owners; it does not mutate their state.",
        cls="subtitle",
        fill="muted",
    )

    owners = [
        ("saga", "teal"),
        ("mission-control", "blue"),
        ("deploy", "green"),
        ("team-execution", "violet"),
    ]
    x = 70
    for owner, color in owners:
        data = model["external_owners"][owner]
        _box(parts, x, 185, 350, 560)
        _pill(parts, x + 24, 215, owner, fill=color)
        _text(parts, x + 24, 285, "Owns", cls="label")
        y = 320
        for item in data.get("owns", []):
            _text(parts, x + 42, y, f"- {item}", max_chars=28, fill="muted", line_height=18)
            y += 48
        if data.get("must_not_own"):
            _text(parts, x + 24, 575, "Must not own", cls="label", fill="rose")
            y = 610
            for item in data["must_not_own"]:
                _text(parts, x + 42, y, f"- {item}", max_chars=28, fill="muted", line_height=18)
                y += 44
        if data.get("saga_holds"):
            _text(parts, x + 24, 575, "Saga holds", cls="label", fill="amber")
            y = 610
            for item in data["saga_holds"]:
                _text(parts, x + 42, y, f"- {item}", max_chars=28, fill="muted", line_height=18)
                y += 44
        x += 370

    _text(
        parts,
        70,
        835,
        "Owner wins when cached Saga pointers disagree with the source system.",
        cls="label",
        fill="muted",
    )
    return _svg_close(parts)


RENDERERS = {
    "lifecycle-atlas": render_lifecycle_atlas,
    "state-readiness-ladder": render_state_readiness_ladder,
    "command-matrix": render_command_matrix,
    "ownership-boundary-map": render_ownership_boundary_map,
}


def render_all(model: dict[str, Any]) -> dict[str, str]:
    missing = set(RENDERERS) - set(model.get("visuals", {}))
    if missing:
        raise ValueError(f"model missing visual definitions: {sorted(missing)}")
    return {visual_id: renderer(model) for visual_id, renderer in RENDERERS.items()}


def _target_path(model: dict[str, Any], visual_id: str, output_dir: Path | None) -> Path:
    filename = Path(model["visuals"][visual_id]["file"]).name
    if output_dir is not None:
        return output_dir / filename
    return REPO_ROOT / model["visuals"][visual_id]["file"]


def write_assets(
    model: dict[str, Any], *, output_dir: Path | None = None, check: bool = False
) -> int:
    rendered = render_all(model)
    failures: list[str] = []

    for visual_id, svg in rendered.items():
        target = _target_path(model, visual_id, output_dir)
        if check:
            if not target.exists():
                failures.append(f"missing {target}")
                continue
            if target.read_text(encoding="utf-8") != svg:
                failures.append(f"stale {target}")
            continue
        target.parent.mkdir(parents=True, exist_ok=True)
        target.write_text(svg, encoding="utf-8")

    if failures:
        for failure in failures:
            print(failure, file=sys.stderr)
        return 1
    return 0


def _build_parser() -> argparse.ArgumentParser:
    parser = argparse.ArgumentParser(description=__doc__)
    parser.add_argument("--model", type=Path, default=MODEL_PATH)
    parser.add_argument("--output-dir", type=Path)
    parser.add_argument("--check", action="store_true")
    return parser


def main(argv: list[str] | None = None) -> int:
    args = _build_parser().parse_args(argv)
    model = _load_model(args.model)
    return write_assets(model, output_dir=args.output_dir, check=args.check)


if __name__ == "__main__":
    sys.exit(main())
